spring:
 datasource:
   url: jdbc:mysql://localhost:3306/discografy
   username: root
   password:
    driver-class-name: com.mysql.cj.jdbc.Driver

 server:
   port: 8008

 jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     dd-auto: update

 cloudinary:
   nameCloud:
   apiKey:
   apiSecret:







